### ISSUE TITLE
No module named 'pytransform'

### ISSUE THREAD

**Issue by Daggerfp21** [Svenskithesource/PyArmor-Unpacker#35]
I keep on getting this error despite having pyarmor installed. Do I need a pytransform file within the directory of the file I want to unpack?

No module named 'pytransform'

**Comment by Svenskithesource** [comment]
The pytransform module will have been delivered with the script, it's either packed with the `.exe` or if you were given the source file it will have a folder `pytransform` in the same dir.

**Comment by Svenskithesource** [comment]
It has to be included somewhere, otherwise, it wouldn't be able to run. Each `pytransform` is unique to its project. When you extract the `.exe` there has to be a `_pytransform.dll` file in the main dir and in the PYZ folder, there will be a `pytransform.pyc` file. Copy that one to the main dir and it should run fine.

**Comment by Daggerfp21** [comment]
> It has to be included somewhere, otherwise, it wouldn't be able to run. Each `pytransform` is unique to its project. When you extract the `.exe` there has to be a `_pytransform.dll` file in the main dir and in the PYZ folder, there will be a `pytransform.pyc` file. Copy that one to the main dir and it should run fine.

I was able to find everything thank you so much, but now the problem is pycdc has some unsopprted opcodes, so i was wondering if there is an alternative?
